server:
  port: 8811

spring:
  datasource:
    url: jdbc:sqlserver://113.190.149.100:1433;databaseName=QLtrungtamtoanhoc1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: duc
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
logging:
  level:
    ROOT: ERROR
    com.da: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

application:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization'
    allow-credentials: true
    max-age: 3600
