server:
  port: 8811

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qltrungtamtoanhoc1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shaiya01

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
logging:
  level:
    ROOT: ERROR
    com.da: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

application:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization'
    allow-credentials: true
    max-age: 3600
